### PR TITLE
Usability features

### PR DESCRIPTION
**Pull request by Kronuz**
Inspired by some features in https://marketplace.visualstudio.com/items?itemName=humao.rest-client, and in the vein of getting things as simple as possible, I added support for a few things:

+ Support MULTIPLE requests in the same file (separated by `###` delimiter)
+ "Native" variables, making easy to define in-file custom variables (starting with `@`)
+ Allow `Host` as default header (but not using it when request has it)
+ HTTP language support for `.http` and `.rest` file extensions and for responses
+ Phantoms for quickly applying "one-click" requests.

### CODE REVIEW

**Comment by pjdietz** [comment]
Thank you so much for all the work you did on this PR!

One small thing I noticed as I'm trying out your version is that the multiple requests feature is not working as intended. It's cutting off the last character of the request when the selection does not end with a `###`.

I think we need to explicitly check for `begin != -1` and `end != -1` in `http_request_command.py`, lines 366, 368, and 370. Otherwise, they evaluate as `True` when -1 and the selection is never set to `selection[being:]` or `selection[:end]`. This was easiest to detect with a file of simple one line requests.

Would you mind double checking this feature? I'd be happy to merge and deploy once that's all set.

Thanks!
—PJ

**Comment by Kronuz** [comment]
Oh, right! For some dumb reason I just assumed `find` would return `False` when I wrote that. I’ll update the pull request to fix it, thank you for noticing

**Comment by pjdietz** [comment]
Looks good! Merged and tagged! Package Control should pick up the new 1.9.0 release soon. Thanks for the PR!

**Comment by Kronuz** [comment]
Great! Thank you!

There’s other issue yet... some times it fails to parse the host, apparently, and there are errors about the connection that simply end up like if nothing was being done, for perfectly valid requests (which as is, later just work). I’ll open an issue later about it.

**Pull request merged**
